"""initial schema

Revision ID: 478a409161f4
Revises:
Create Date: 2026-09-05 15:06:34.168138
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "478a409161f4"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "deals",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("company_name", sa.String(length=200), nullable=False),
        sa.Column("industry", sa.String(length=120), nullable=False),
        sa.Column("purchase_price", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column(
            "purchase_price_basis",
            sa.Enum("enterprise_value", "equity_price", name="purchase_price_basis", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column("purchase_date", sa.Date(), nullable=True),
        sa.Column("debt_amount", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("equity_amount", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("debt_assumed", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("cash_acquired", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("interest_rate_pct", sa.Numeric(precision=8, scale=4), nullable=False),
        sa.Column("amortization_years", sa.Integer(), nullable=False),
        sa.Column("payments_per_year", sa.Integer(), nullable=False),
        sa.Column("covenant_dscr_threshold", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column(
            "status",
            sa.Enum("draft", "processing", "verified", "reported", name="deal_status", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("fiscal_year_end_month", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("deals", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_deals_owner_id"), ["owner_id"], unique=False)

    op.create_table(
        "user_sessions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=128), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    with op.batch_alter_table("user_sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_sessions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "audit_events",
        sa.Column("deal_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("object_type", sa.String(length=40), nullable=False),
        sa.Column("object_id", sa.Uuid(), nullable=True),
        sa.Column("summary", sa.String(length=500), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["deal_id"], ["deals.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.create_index("ix_audit_deal_created", ["deal_id", "created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_events_event_type"), ["event_type"], unique=False)

    op.create_table(
        "documents",
        sa.Column("deal_id", sa.Uuid(), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column(
            "doc_type",
            sa.Enum(
                "cim",
                "financial_statements",
                "acquisition_model",
                "customer_revenue",
                "debt_term_sheet",
                "customer_contract",
                "other",
                "unknown",
                name="document_type",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "classification_source",
            sa.Enum("rule", "ai", "user", name="classification_source", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column("classification_confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "uploaded",
                "queued",
                "parsing",
                "extracting",
                "ready",
                "failed",
                name="document_status",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("status_detail", sa.Text(), nullable=True),
        sa.Column("current_version_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["deal_id"], ["deals.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_documents_deal_id"), ["deal_id"], unique=False)

    op.create_table(
        "reports",
        sa.Column("deal_id", sa.Uuid(), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("draft", "validated", "failed_validation", name="report_status", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column(
            "outcome",
            sa.Enum(
                "additional_diligence_required",
                "material_concerns_identified",
                "assumptions_require_revision",
                "ready_for_ic_review",
                name="review_outcome",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("sections", sa.JSON(), nullable=False),
        sa.Column("validation", sa.JSON(), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("model", sa.String(length=80), nullable=False),
        sa.Column("prompt_version", sa.String(length=20), nullable=False),
        sa.Column("schema_version", sa.String(length=20), nullable=False),
        sa.Column("engine_version", sa.String(length=20), nullable=False),
        sa.Column("input_snapshot", sa.JSON(), nullable=False),
        sa.Column("generated_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["deal_id"], ["deals.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["generated_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("deal_id", "version_no", name="uq_report_version"),
    )
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_reports_deal_id"), ["deal_id"], unique=False)

    op.create_table(
        "scenarios",
        sa.Column("deal_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("base", "downside", "severe_downside", "custom", name="scenario_kind", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_seed", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["deal_id"], ["deals.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("scenarios", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_scenarios_deal_id"), ["deal_id"], unique=False)

    op.create_table(
        "document_versions",
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("extension", sa.String(length=10), nullable=False),
        sa.Column("mime_declared", sa.String(length=120), nullable=True),
        sa.Column("mime_detected", sa.String(length=120), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("sheet_count", sa.Integer(), nullable=True),
        sa.Column("row_count", sa.Integer(), nullable=True),
        sa.Column("parse_meta", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "version_no", name="uq_document_version"),
    )
    with op.batch_alter_table("document_versions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_document_versions_document_id"), ["document_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_document_versions_sha256"), ["sha256"], unique=False)

    op.create_table(
        "extraction_runs",
        sa.Column("deal_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=True),
        sa.Column(
            "run_type",
            sa.Enum("classify", "extract", "verify", "report", name="run_type", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("succeeded", "failed", "invalid_output", name="run_status", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("model", sa.String(length=80), nullable=False),
        sa.Column("prompt_version", sa.String(length=20), nullable=False),
        sa.Column("schema_version", sa.String(length=20), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("raw_output", sa.JSON(), nullable=False),
        sa.Column("usage", sa.JSON(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["deal_id"], ["deals.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("extraction_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_extraction_runs_deal_id"), ["deal_id"], unique=False)

    op.create_table(
        "financial_periods",
        sa.Column("deal_id", sa.Uuid(), nullable=False),
        sa.Column("label", sa.String(length=20), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("source_document_id", sa.Uuid(), nullable=True),
        sa.Column("source_sheet", sa.String(length=80), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["deal_id"], ["deals.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_document_id"], ["documents.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("deal_id", "label", name="uq_period_label"),
    )
    with op.batch_alter_table("financial_periods", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_financial_periods_deal_id"), ["deal_id"], unique=False)

    op.create_table(
        "processing_jobs",
        sa.Column("deal_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=True),
        sa.Column(
            "job_type",
            sa.Enum("process_document", "analyze_deal", "generate_report", name="job_type", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("queued", "running", "succeeded", "failed", "cancelled", name="job_status", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("step", sa.String(length=120), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("log", sa.JSON(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["deal_id"], ["deals.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("processing_jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_processing_jobs_deal_id"), ["deal_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_processing_jobs_status"), ["status"], unique=False)

    op.create_table(
        "scenario_assumptions",
        sa.Column("scenario_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("label", sa.String(length=160), nullable=False),
        sa.Column("value", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column(
            "unit",
            sa.Enum(
                "usd", "pct", "multiple", "months", "years", "count", "text", name="assumption_unit", native_enum=False, length=40
            ),
            nullable=False,
        ),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["scenario_id"], ["scenarios.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scenario_id", "key", name="uq_scenario_assumption"),
    )
    with op.batch_alter_table("scenario_assumptions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_scenario_assumptions_scenario_id"), ["scenario_id"], unique=False)

    op.create_table(
        "scenario_results",
        sa.Column("scenario_id", sa.Uuid(), nullable=False),
        sa.Column("run_no", sa.Integer(), nullable=False),
        sa.Column("engine_version", sa.String(length=20), nullable=False),
        sa.Column("input_snapshot", sa.JSON(), nullable=False),
        sa.Column("outputs", sa.JSON(), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("run_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["scenario_id"], ["scenarios.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scenario_id", "run_no", name="uq_scenario_run"),
    )
    with op.batch_alter_table("scenario_results", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_scenario_results_scenario_id"), ["scenario_id"], unique=False)

    op.create_table(
        "evidence",
        sa.Column("deal_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("document_version_id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "page_text",
                "table_cell",
                "sheet_cell",
                "sheet_row",
                "csv_row",
                "csv_aggregate",
                name="evidence_kind",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("locator", sa.JSON(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("structured", sa.JSON(), nullable=True),
        sa.Column("contains_instruction_text", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["deal_id"], ["deals.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["document_version_id"], ["document_versions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("evidence", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_evidence_deal_id"), ["deal_id"], unique=False)
        batch_op.create_index("ix_evidence_doc_chunk", ["document_id", "chunk_index"], unique=False)
        batch_op.create_index(batch_op.f("ix_evidence_document_id"), ["document_id"], unique=False)

    op.create_table(
        "financial_metrics",
        sa.Column("deal_id", sa.Uuid(), nullable=False),
        sa.Column("period_id", sa.Uuid(), nullable=True),
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("label", sa.String(length=160), nullable=False),
        sa.Column("value", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("raw_value", sa.String(length=80), nullable=True),
        sa.Column(
            "unit",
            sa.Enum(
                "usd", "pct", "multiple", "months", "years", "count", "text", name="metric_unit", native_enum=False, length=40
            ),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum("extracted", "calculated", "verified", "scenario", name="metric_source", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column("formula", sa.Text(), nullable=True),
        sa.Column("input_snapshot", sa.JSON(), nullable=False),
        sa.Column("evidence_ids", sa.JSON(), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("requires_review", sa.Boolean(), nullable=False),
        sa.Column("missing_inputs", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["deal_id"], ["deals.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["period_id"], ["financial_periods.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("financial_metrics", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_financial_metrics_deal_id"), ["deal_id"], unique=False)
        batch_op.create_index("ix_metric_deal_key", ["deal_id", "key", "period_id", "source"], unique=False)

    op.create_table(
        "claims",
        sa.Column("deal_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("extraction_run_id", sa.Uuid(), nullable=True),
        sa.Column("verification_run_id", sa.Uuid(), nullable=True),
        sa.Column("source_evidence_id", sa.Uuid(), nullable=True),
        sa.Column("key", sa.String(length=120), nullable=False),
        sa.Column("claim_text", sa.Text(), nullable=False),
        sa.Column(
            "claim_type",
            sa.Enum(
                "revenue",
                "revenue_growth",
                "customer_concentration",
                "recurring_revenue",
                "churn",
                "adjusted_ebitda",
                "addback",
                "gross_margin",
                "operating_margin",
                "margin_improvement",
                "forecast",
                "contract_term",
                "debt_term",
                "one_time_expense",
                "other",
                name="claim_type",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("metric_key", sa.String(length=80), nullable=True),
        sa.Column("period_label", sa.String(length=20), nullable=True),
        sa.Column("claimed_value", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column(
            "claimed_unit",
            sa.Enum(
                "usd", "pct", "multiple", "months", "years", "count", "text", name="claim_unit", native_enum=False, length=40
            ),
            nullable=False,
        ),
        sa.Column("normalized", sa.JSON(), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "supported",
                "contradicted",
                "unsupported",
                "review_required",
                name="claim_status",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("status_rationale", sa.Text(), nullable=True),
        sa.Column("status_rule", sa.String(length=120), nullable=True),
        sa.Column("verified_value", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column(
            "verified_unit",
            sa.Enum(
                "usd",
                "pct",
                "multiple",
                "months",
                "years",
                "count",
                "text",
                name="claim_unit_verified",
                native_enum=False,
                length=40,
            ),
            nullable=True,
        ),
        sa.Column("verified_metric_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["deal_id"], ["deals.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["extraction_run_id"], ["extraction_runs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["source_evidence_id"], ["evidence.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["verification_run_id"], ["extraction_runs.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("claims", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_claims_deal_id"), ["deal_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_claims_document_id"), ["document_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_claims_metric_key"), ["metric_key"], unique=False)
        batch_op.create_index(batch_op.f("ix_claims_status"), ["status"], unique=False)

    op.create_table(
        "report_citations",
        sa.Column("report_id", sa.Uuid(), nullable=False),
        sa.Column("section_key", sa.String(length=80), nullable=False),
        sa.Column("statement_index", sa.Integer(), nullable=False),
        sa.Column("kind", sa.Enum("evidence", "calculation", name="citation_kind", native_enum=False, length=40), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=True),
        sa.Column("metric_id", sa.Uuid(), nullable=True),
        sa.Column("resolved", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["evidence_id"], ["evidence.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["metric_id"], ["financial_metrics.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["report_id"], ["reports.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("report_citations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_report_citations_report_id"), ["report_id"], unique=False)

    op.create_table(
        "adjustments",
        sa.Column("deal_id", sa.Uuid(), nullable=False),
        sa.Column("claim_id", sa.Uuid(), nullable=True),
        sa.Column("key", sa.String(length=120), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("amount", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column(
            "direction",
            sa.Enum("add_back", "downward", name="adjustment_direction", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column("period_label", sa.String(length=20), nullable=False),
        sa.Column("seller_rationale", sa.Text(), nullable=True),
        sa.Column(
            "decision",
            sa.Enum(
                "pending",
                "accepted",
                "rejected",
                "review_required",
                "unsupported",
                name="adjustment_decision",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("decision_rationale", sa.Text(), nullable=True),
        sa.Column("decision_rule", sa.String(length=120), nullable=True),
        sa.Column("decided_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("evidence_ids", sa.JSON(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["claim_id"], ["claims.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["deal_id"], ["deals.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["decided_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("adjustments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_adjustments_deal_id"), ["deal_id"], unique=False)

    op.create_table(
        "claim_evidence_links",
        sa.Column("claim_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("source", "supporting", "contradicting", name="link_role", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column("relevance", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["claim_id"], ["claims.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["evidence_id"], ["evidence.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("claim_id", "evidence_id", "role", name="uq_claim_evidence_role"),
    )
    with op.batch_alter_table("claim_evidence_links", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_claim_evidence_links_claim_id"), ["claim_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_claim_evidence_links_evidence_id"), ["evidence_id"], unique=False)

    op.create_table(
        "findings",
        sa.Column("deal_id", sa.Uuid(), nullable=False),
        sa.Column("claim_id", sa.Uuid(), nullable=True),
        sa.Column("key", sa.String(length=120), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "contradiction",
                "unsupported_assumption",
                "missing_document",
                "covenant_warning",
                "document_integrity",
                "concentration",
                "risk",
                name="finding_kind",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.Enum("low", "medium", "high", "critical", name="severity", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.Column("evidence_ids", sa.JSON(), nullable=False),
        sa.Column("metric_ids", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("open", "acknowledged", "resolved", name="finding_status", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["claim_id"], ["claims.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["deal_id"], ["deals.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("findings", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_findings_deal_id"), ["deal_id"], unique=False)

    op.create_table(
        "reviewer_comments",
        sa.Column("deal_id", sa.Uuid(), nullable=False),
        sa.Column("claim_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["claim_id"], ["claims.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["deal_id"], ["deals.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("reviewer_comments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_reviewer_comments_deal_id"), ["deal_id"], unique=False)

    op.create_table(
        "review_decisions",
        sa.Column("deal_id", sa.Uuid(), nullable=False),
        sa.Column("claim_id", sa.Uuid(), nullable=True),
        sa.Column("adjustment_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "action",
            sa.Enum("accept", "reject", "correct", "undo", name="review_action", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column("resulting_status", sa.String(length=40), nullable=True),
        sa.Column("corrected_value", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column(
            "corrected_unit",
            sa.Enum(
                "usd", "pct", "multiple", "months", "years", "count", "text", name="corrected_unit", native_enum=False, length=40
            ),
            nullable=True,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("supersedes_id", sa.Uuid(), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["adjustment_id"], ["adjustments.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["claim_id"], ["claims.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["deal_id"], ["deals.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["supersedes_id"], ["review_decisions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("review_decisions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_review_decisions_claim_id"), ["claim_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_review_decisions_deal_id"), ["deal_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("review_decisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_review_decisions_deal_id"))
        batch_op.drop_index(batch_op.f("ix_review_decisions_claim_id"))

    op.drop_table("review_decisions")
    with op.batch_alter_table("reviewer_comments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reviewer_comments_deal_id"))

    op.drop_table("reviewer_comments")
    with op.batch_alter_table("findings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_findings_deal_id"))

    op.drop_table("findings")
    with op.batch_alter_table("claim_evidence_links", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_claim_evidence_links_evidence_id"))
        batch_op.drop_index(batch_op.f("ix_claim_evidence_links_claim_id"))

    op.drop_table("claim_evidence_links")
    with op.batch_alter_table("adjustments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_adjustments_deal_id"))

    op.drop_table("adjustments")
    with op.batch_alter_table("report_citations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_report_citations_report_id"))

    op.drop_table("report_citations")
    with op.batch_alter_table("claims", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_claims_status"))
        batch_op.drop_index(batch_op.f("ix_claims_metric_key"))
        batch_op.drop_index(batch_op.f("ix_claims_document_id"))
        batch_op.drop_index(batch_op.f("ix_claims_deal_id"))

    op.drop_table("claims")
    with op.batch_alter_table("financial_metrics", schema=None) as batch_op:
        batch_op.drop_index("ix_metric_deal_key")
        batch_op.drop_index(batch_op.f("ix_financial_metrics_deal_id"))

    op.drop_table("financial_metrics")
    with op.batch_alter_table("evidence", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_evidence_document_id"))
        batch_op.drop_index("ix_evidence_doc_chunk")
        batch_op.drop_index(batch_op.f("ix_evidence_deal_id"))

    op.drop_table("evidence")
    with op.batch_alter_table("scenario_results", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scenario_results_scenario_id"))

    op.drop_table("scenario_results")
    with op.batch_alter_table("scenario_assumptions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scenario_assumptions_scenario_id"))

    op.drop_table("scenario_assumptions")
    with op.batch_alter_table("processing_jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_processing_jobs_status"))
        batch_op.drop_index(batch_op.f("ix_processing_jobs_deal_id"))

    op.drop_table("processing_jobs")
    with op.batch_alter_table("financial_periods", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_financial_periods_deal_id"))

    op.drop_table("financial_periods")
    with op.batch_alter_table("extraction_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_extraction_runs_deal_id"))

    op.drop_table("extraction_runs")
    with op.batch_alter_table("document_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_document_versions_sha256"))
        batch_op.drop_index(batch_op.f("ix_document_versions_document_id"))

    op.drop_table("document_versions")
    with op.batch_alter_table("scenarios", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scenarios_deal_id"))

    op.drop_table("scenarios")
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reports_deal_id"))

    op.drop_table("reports")
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_documents_deal_id"))

    op.drop_table("documents")
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_events_event_type"))
        batch_op.drop_index("ix_audit_deal_created")

    op.drop_table("audit_events")
    with op.batch_alter_table("user_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_sessions_user_id"))

    op.drop_table("user_sessions")
    with op.batch_alter_table("deals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_deals_owner_id"))

    op.drop_table("deals")
    op.drop_table("users")
    # ### end Alembic commands ###
