"""deal questions

Revision ID: 96ad0d1ac962
Revises: 478a409161f4
Create Date: 2026-09-05 16:08:02.411485
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "96ad0d1ac962"
down_revision = "478a409161f4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deal_questions",
        sa.Column("deal_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("intents", sa.JSON(), nullable=False),
        sa.Column("statements", sa.JSON(), nullable=False),
        sa.Column("grounded", sa.Boolean(), nullable=False),
        sa.Column("validation", sa.JSON(), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("model", sa.String(length=80), nullable=False),
        sa.Column("prompt_version", sa.String(length=20), nullable=False),
        sa.Column("schema_version", sa.String(length=20), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["deal_id"], ["deals.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("deal_questions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_deal_questions_deal_id"), ["deal_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("deal_questions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_deal_questions_deal_id"))

    op.drop_table("deal_questions")
    # ### end Alembic commands ###
